version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-ecommerce
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d # Executa os scripts automaticamente na ordem (01, 02...)
volumes:
  postgres_data: